# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

# Install GSL, solution from https://stackoverflow.com/a/49165163
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev